---
# tasks file for symantec-endpoint-protection

- name: Enshure zip installed
  yum:
    name: unzip
    state: present

- name: Check if SAV is installed
  stat:
    path: /opt/Symantec/symantec_antivirus/sav
  register: installed

- name: test version
  command: /opt/Symantec/symantec_antivirus/sav info -p
  register: out
  when: installed.stat.exists

- name: print info
  debug:
    msg: out.stdout_lines
  when: installed.stat.exists

- name: Create Temp Folder
  file:
    state: directory
    path: /tmp/sep/
  when: not installed.stat.exists


- name: Get SEV Tarball
  get_url:
    url: '{{ remote_tar_loc }}'
    dest: /tmp/sep/sep.zip
  when: not installed.stat.exists
  register: get_sev

# Unarchive does not work
- name: Place endpoint protection agent installation files
  command: 'unzip /tmp/sep/sep.zip -d /tmp/sep/'
  when: get_sev.changed


- name: Create Prereq group
  group:
    gid: 594
    name: avdefs
    state: present

- name: Install Dependecies
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - glibc

- name: mark SEP +x
  file:
    path: /tmp/sep/install.sh
    mode: 0755

- name: Install SEP
  command: /tmp/sep/install.sh -i
  when: not installed.stat.exists

- name: Enshure rtvscand started
  service:
    name: rtvscand
    state: started
    enabled: True

- name: Enshure symcfgd started
  service:
    name: symcfgd
    state: started
    enabled: True

- name: Enshure smcd started
  service:
    name: smcd
    state: started
    enabled: True

- name: Check log location
  file:
    path: /opt/Symantec/log
    state: directory
  register: log_link

- name: Move file over
  command: 'cp /var/log/symantec/* /opt/Symantec/log/'
  register: move_file
  when: log_link.changed

- name: Delete original log location
  file:
    path: /var/log/symantec
    state: absent
  when: move_file.changed

- name: Link to log location
  file:
    path: /var/log/symantec
    src: /opt/Symantec/log
    state: link
  when: move_file.changed

- name: Delete original installer
  file:
    path: /tmp/sep
    state: absent
  when: not installed.stat.exists
