---
- name: Install Splunk Agent
  hosts: all
  vars:
    - splunk_admin_password: changeme
    - splunk_rpm_key: http://satellite.mydomain.com/mykey
    - splunk_host: MY_HOST
  tasks:

    - name: Add RPM key
      rpm_key:
        key: '{{ splunk_rpm_key }}'
        state: present

    - name: Install Splunk
      yum:
        name: splunkforwarder
      notify:
        - Start Splunk
        - Enable Splunk
        - Configure Splunk

  handlers:
    - name: Start Splunk
      command: '/opt/splunkforwarder/bin/splunk start --accept-license'

    - name: Enable Splunk
      command: '/opt/splunkforwarder/bin/splunk enable boot-start'

    - name: Enable Splunk
      command: '/opt/splunkforwarder/bin/splunk set deploy-poll {{ splunk_host }}:8089 -auth admin:{{ splunk_admin_password }}'
