---
# This role conains tasks to deploy the Oracle Enterprise Manager Agent


- name: checking emagent port
  wait_for:
    host: '{{ inventory_hostname }} '
    port: '{{ emagent_port }} '
    state: stopped
    timeout: 1
  tags: check

- name: installing dependencies
  yum:
    name: '{{ item }} '
    state: present
  with_items: '{{emagent_packages}}'
  tags: install

- name: creating emagent group
  group:
    name: '{{ _emagent.group }}'
    state: present
  tags: user

- name: creating emagent user
  user:
    name: '{{ _emagent.user }}'
    group: '{{ _emagent.group }}'
    state: present
  tags: user

- name: creating base directory
  file:
    path: '{{ emagent_base }}'
    state: directory
    owner: '{{ _emagent.user }}'
    group: '{{ _emagent.group }}'
  tags: install

- name: creating temporary directory
  file:
    path: /tmp/ansible_emagent
    state: directory
    owner: '{{ _emagent.user }}'
    group: '{{ _emagent.group }}'
  tags: install

# - name: uploading emagent installer
#   unarchive:
#     src: files/{{ emagent_version }}_AgentCore_{{ _emagent.platform[ansible_system][ansible_architecture] }}.zip
#     dest: /tmp/ansible_emagent
#   tags: install

- name: get installer
  get_url:
    url: '{{ oem_zip_path }}'
    dest: /tmp/oem_agent_core.zip
    mode: 0644

- name: uploading emagent installer
  command: 'unzip /tmp/oem_agent_core.zip -d /tmp/ansible_emagent'
  tags: install

# Need to test this
- name: installing emagent
  shell: cd /tmp/ansible_emagent;
         su -{{ _emagent.user }};
         ./agentDeploy.sh
         AGENT_BASE_DIR={{ emagent_base }}/{{ emagent_dir }}
         AGENT_INSTANCE_HOME={{ emagent_base }}/{{ emagent_dir }}/agent_inst
         ORACLE_HOSTNAME={{ inventory_hostname }}
         AGENT_PORT={{ emagent_port }}
         OMS_HOST={{ emagent_oms_host }}
         EM_UPLOAD_PORT={{ emagent_oms_port }}
         AGENT_REGISTRATION_PASSWORD={{ emagent_oms_password }}
  #become_user: "{{ _emagent.user }}"
  tags: install

- name: removing oem agent installer
  file:
    path: /tmp/ansible_emagent
    state: absent
  tags: install

- name: executing root.sh configuration script
  shell: "{{ emagent_base }}/{{ emagent_dir }}/core/{{ emagent_version }}/root.sh"
  tags: install

- name: executing orainstRoot.sh configuration script
  shell: "{{ _emagent.users_home }}/{{ _emagent.user }}/oraInventory/orainstRoot.sh"
  tags: install
